[package]
name = "bazel-language-server"
description = "Language server for Bazel build files"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"
keywords = ["bazel", "lsp", "starlark", "language-server", "build"]
categories = ["development-tools"]

[[bin]]
name = "bazel-language-server"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
bls-bazel.workspace = true
bls-index.workspace = true
clap.workspace = true
lsp-server.workspace = true
lsp-types.workspace = true
serde.workspace = true
serde_json.workspace = true
starlark-cst.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
