[package]
name = "bazel-language-server"
version = "0.0.1"
edition = "2024"
rust-version = "1.85"
authors = ["Barrett Ruth <br@barrettruth.com>"]
description = "Language server for Bazel build files"
license = "GPL-3.0-only"
repository = "https://github.com/barrettruth/bazel-language-server"
readme = "README.md"
keywords = ["bazel", "lsp", "starlark", "language-server", "build"]
categories = ["development-tools"]

[dependencies]
anyhow = "1"
arc-swap = "1"
clap = { version = "4", features = ["derive"] }
lsp-server = "0.10"
lsp-types = { version = "0.11", package = "gen-lsp-types", features = [
  "fluent-uri",
] }
rustc-hash = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
starlark-cst = "0.0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
walkdir = "2"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = "warn"

[profile.release]
opt-level = 3
