[package]
name = "bls-bazel"
description = "Bazel workspace discovery and invocation for the Bazel language server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
serde = { workspace = true }
tracing.workspace = true

[lints]
workspace = true
