//! The graph tier: the targets only Bazel can name.
//!
//! A legacy macro computes its targets' names when Bazel evaluates it, so
//! `//lib:from_legacy_0` exists in the build and appears nowhere in the source.
//! No parser can find it and no amount of work on the static tier will change
//! that — asking Bazel is the only way, which is what this module does.
//!
//! Bazel is asked through [`BazelClient::stream`] and decoded as the bytes
//! arrive. Slurping the stream first costs thirteen times the memory for the
//! same wall time: 442 MB against 34 MB over 240,000 targets. Decoding is not
//! the constraint either way — prost manages 324 MB/s and Bazel writes at 52.

use std::path::PathBuf;
use std::sync::Arc;

use anyhow::Result;
use bytes::{Buf, BytesMut};
use prost::{DecodeError, Message};

use crate::bazel::{BazelClient, Interrupt, Outcome};
use crate::index::{Target, Tier};

mod proto {
    //! Bazel's own schema, vendored under `proto/` and generated by `build.rs`.
    //!
    //! Most of it is unused: the light tier wants a name, a rule class and a
    //! location, and the rest of `build.proto` comes along because a schema is
    //! not something to edit down by hand.
    #![allow(dead_code, clippy::pedantic, clippy::all)]

    pub mod stardoc_output {
        include!(concat!(env!("OUT_DIR"), "/stardoc_output.rs"));
    }
    pub mod blaze_query {
        include!(concat!(env!("OUT_DIR"), "/blaze_query.rs"));
    }
}

/// Bazel's word for a target, kept distinct from the index's own.
use proto::blaze_query::{Target as Reported, target::Discriminator};

/// The query that feeds the graph tier, and the flags that keep it affordable.
///
/// Pruning attributes is a tenfold cut — 53.7 MB to 5.4 MB, 0.89 s to 0.42 s at
/// 60k targets — and what survives still carries the name, the rule class and
/// the location, which is the whole of the light tier.
/// `--proto:rule_inputs_and_outputs` defaults on and is the expensive half of
/// what would otherwise remain. Rule schemas are a second, narrower query for
/// the packages that want them, because they are the other tenfold.
const QUERY: &[&str] = &[
    "query",
    "--output=streamed_proto",
    "--proto:output_rule_attrs=",
    "--noproto:rule_inputs_and_outputs",
    "--order_output=no",
    "--noimplicit_deps",
    "--notool_deps",
    "--keep_going",
    "//...",
];

/// A varint is at most ten bytes, which is how a short read is told from a bad
/// one: `decode_length_delimiter` reports both the same way.
const MAX_VARINT: usize = 10;

/// One run of [`QUERY`].
pub struct Query {
    /// Empty where Bazel declined; `outcome` says so.
    pub tier: Tier,
    pub outcome: Outcome,
}

/// Ask Bazel for the graph, decoding it as it arrives.
///
/// `started` receives the [`Interrupt`] before the first byte, so a caller that
/// supersedes this run can stop it.
///
/// # Errors
///
/// If Bazel cannot be run, or answered with something that is not the protocol.
pub fn query(client: &BazelClient, started: impl FnOnce(Interrupt)) -> Result<Query> {
    let mut decoder = Decoder::default();
    let outcome = client.stream(QUERY, started, &mut |chunk| decoder.push(chunk))?;
    // A refused or interrupted query wrote a truncated stream. The caller
    // reports the refusal, which is the useful half; the truncation is a
    // consequence of it and saying both would bury the cause.
    let tier = if outcome.ok() {
        decoder.finish()?
    } else {
        Tier::default()
    };
    Ok(Query { tier, outcome })
}

/// Turns the chunks Bazel writes into targets, holding one partial message at
/// most.
#[derive(Default)]
struct Decoder {
    pending: BytesMut,
    tier: Tier,
    /// The first thing that went wrong, carried to [`Decoder::finish`] because
    /// the sink [`BazelClient::stream`] writes into cannot return one.
    failed: Option<DecodeError>,
}

impl Decoder {
    fn push(&mut self, chunk: &[u8]) {
        if self.failed.is_some() {
            return;
        }
        self.pending.extend_from_slice(chunk);
        self.failed = self.drain(false).err();
    }

    /// Every target in the stream, or the first thing that went wrong in it.
    fn finish(mut self) -> Result<Tier> {
        if let Some(failed) = self.failed {
            return Err(failed.into());
        }
        self.drain(true)?;
        anyhow::ensure!(
            self.pending.is_empty(),
            "{} bytes of a target that never finished arriving",
            self.pending.len()
        );
        Ok(self.tier)
    }

    /// Pull every complete message out of `pending`.
    ///
    /// `--output=streamed_proto` is a bare sequence of `varint(len) || Target`
    /// rather than a message of its own, so there is nothing to hand
    /// `Message::decode` whole. `decode_length_delimited` is the trap here: on
    /// a pipe it reports a short read and a corrupt stream identically, so the
    /// length is read from a copy of the cursor and `pending` is left untouched
    /// until the whole body has arrived.
    fn drain(&mut self, eof: bool) -> Result<(), DecodeError> {
        while !self.pending.is_empty() {
            let mut peek: &[u8] = &self.pending[..];
            let len = match prost::decode_length_delimiter(&mut peek) {
                Ok(len) => len,
                Err(_) if !eof && self.pending.len() < MAX_VARINT => return Ok(()),
                Err(err) => return Err(err),
            };
            let header = self.pending.len() - peek.len();
            if self.pending.len() - header < len {
                return Ok(());
            }
            self.pending.advance(header);
            let frame = self.pending.split_to(len);
            if let Some((label, target)) = declared(&Reported::decode(&frame[..])?) {
                self.tier.targets.insert(label, target);
            }
        }
        Ok(())
    }
}

/// What a target contributes to the light tier, where it contributes anything.
///
/// `//...` names rules, so the other kinds arrive only from a caller that asked
/// for them, and a rule Bazel cannot place is one nothing can navigate to.
fn declared(reported: &Reported) -> Option<(String, Target)> {
    if Discriminator::try_from(reported.r#type).ok()? != Discriminator::Rule {
        return None;
    }
    let rule = reported.rule.as_ref()?;
    let (file, line, column) = located(rule.location.as_deref()?)?;
    let name = rule.name.rsplit_once(':')?.1;
    Some((
        rule.name.clone(),
        Target {
            name: name.into(),
            rule: rule.rule_class.as_str().into(),
            file: Arc::from(file.as_path()),
            // Bazel counts from one and LSP from zero. The span is empty
            // because there is nothing to cover: Bazel places a target at the
            // call that produced it, and for everything this tier exists for —
            // the targets a macro computes — no name is written there at all.
            // An empty range is a cursor position in every client, which is
            // the honest answer to "where does this come from".
            line: line.saturating_sub(1),
            character: column.saturating_sub(1),
            length: 0,
        },
    ))
}

/// The file, line and column out of Bazel's `<path>:<line>:<column>`.
///
/// Split from the right, because the path is absolute and a directory may
/// contain a colon. The column points at the call's opening parenthesis, and is
/// read as UTF-16 because a rule name is an identifier and the text before it
/// on that line is indentation — the two encodings cannot disagree there.
fn located(raw: &str) -> Option<(PathBuf, u32, u32)> {
    let (head, tail) = raw.rsplit_once(':')?;
    if let Some((path, line)) = head.rsplit_once(':')
        && let Ok(line) = line.parse()
    {
        return Some((PathBuf::from(path), line, tail.parse().unwrap_or(1)));
    }
    Some((PathBuf::from(head), tail.parse().ok()?, 1))
}

#[cfg(test)]
mod tests {
    use super::*;
    use proto::blaze_query::Rule;
    use std::path::Path;

    fn rule(name: &str, class: &str, location: &str) -> Vec<u8> {
        Reported {
            r#type: Discriminator::Rule as i32,
            rule: Some(Rule {
                name: name.to_string(),
                rule_class: class.to_string(),
                location: Some(location.to_string()),
                ..Default::default()
            }),
            ..Default::default()
        }
        .encode_length_delimited_to_vec()
    }

    fn decode(stream: &[u8], chunk: usize) -> Result<Tier> {
        let mut decoder = Decoder::default();
        for part in stream.chunks(chunk) {
            decoder.push(part);
        }
        decoder.finish()
    }

    /// The pipe hands over whatever it has, so a message is split across reads
    /// far more often than not. Every boundary has to behave the same.
    #[test]
    fn a_target_split_across_reads_still_decodes() {
        let mut stream = rule("//lib:srcs", "filegroup", "/ws/lib/BUILD.bazel:12:1");
        stream.extend(rule("//app:bin", "cc_binary", "/ws/app/BUILD.bazel:3:1"));

        let whole = decode(&stream, stream.len()).expect("one read");
        assert_eq!(whole.len(), 2);
        let srcs = whole.targets.get("//lib:srcs").expect("the first target");
        assert_eq!(&*srcs.name, "srcs");
        assert_eq!(&*srcs.rule, "filegroup");
        assert_eq!(&*srcs.file, Path::new("/ws/lib/BUILD.bazel"));
        // Bazel said 12:1; LSP counts from zero, and the span is empty because
        // no name is written at a call site.
        assert_eq!((srcs.line, srcs.character, srcs.length), (11, 0, 0));

        let labels = |tier: &Tier| {
            let mut found: Vec<_> = tier.targets.keys().cloned().collect();
            found.sort_unstable();
            found
        };
        for chunk in 1..=stream.len() {
            assert_eq!(
                labels(&decode(&stream, chunk).expect("every boundary")),
                labels(&whole)
            );
        }
    }

    /// The stream carries no count, so a message cut short is only visible as
    /// bytes left over. Reporting nothing would present a partial graph as the
    /// whole one, which invariant 4 rates worse than reporting no graph at all.
    #[test]
    fn a_truncated_stream_is_an_error() {
        let stream = rule("//lib:srcs", "filegroup", "/ws/lib/BUILD.bazel:1:1");
        for cut in 1..stream.len() {
            assert!(
                decode(&stream[..cut], stream.len()).is_err(),
                "{cut} of {} bytes read as complete",
                stream.len()
            );
        }
    }

    #[test]
    fn a_target_that_is_not_a_rule_contributes_nothing() {
        let source = Reported {
            r#type: Discriminator::SourceFile as i32,
            source_file: Some(proto::blaze_query::SourceFile {
                name: "//lib:a.txt".to_string(),
                location: Some("/ws/lib/BUILD.bazel:1:1".to_string()),
                ..Default::default()
            }),
            ..Default::default()
        }
        .encode_length_delimited_to_vec();
        assert_eq!(decode(&source, source.len()).expect("a stream").len(), 0);
    }

    /// A rule Bazel places nowhere cannot be navigated to, and a label in a
    /// list that goes nowhere when clicked is worse than a shorter list.
    #[test]
    fn a_rule_without_a_location_contributes_nothing() {
        let placeless = Reported {
            r#type: Discriminator::Rule as i32,
            rule: Some(Rule {
                name: "//lib:srcs".to_string(),
                rule_class: "filegroup".to_string(),
                location: None,
                ..Default::default()
            }),
            ..Default::default()
        }
        .encode_length_delimited_to_vec();
        assert_eq!(decode(&placeless, 1).expect("a stream").len(), 0);
    }

    #[test]
    fn a_location_keeps_its_path_and_line() {
        assert_eq!(
            located("/ws/lib/BUILD.bazel:12:1"),
            Some((PathBuf::from("/ws/lib/BUILD.bazel"), 12, 1))
        );
        // Bazel writes a column, and has not always. Both name the same line.
        assert_eq!(
            located("/ws/lib/BUILD.bazel:12"),
            Some((PathBuf::from("/ws/lib/BUILD.bazel"), 12, 1))
        );
        // A directory may contain a colon, so the split has to come from the
        // right and the path is whatever is left.
        assert_eq!(
            located("/ws/a:b/BUILD.bazel:7:3"),
            Some((PathBuf::from("/ws/a:b/BUILD.bazel"), 7, 3))
        );
        assert_eq!(located("/ws/lib/BUILD.bazel"), None);
    }
}
